// ============================================================
// 精算公式注册表 — 全部公式条目
// 数据源：pdf_pptx/final/chapter*_clean.md（8章课件内容）
// ============================================================

import type { FormulaEntry } from "./types";

// ================================================================
// 第一章：生存分布与生命表 (chapter1_clean.md)
// ================================================================

const CH1_FORMULAS: FormulaEntry[] = [
  {
    id: "mu_t",
    symbol: "μ(t)",
    latex: "\\mu(t)",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "死亡力",
    definition: "新生儿的死亡力函数：μ(t) = f_X(t) / s(t)",
    formulaLatex: "\\mu(t) = \\frac{f_X(t)}{1 - F_X(t)} = -\\frac{s'(t)}{s(t)}",
    inputs: [],
    outputs: [{ name: "value", type: "float", label: "死亡力" }],
    dependencies: [],
    isLeaf: true,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "survival_s",
    symbol: "s(t)",
    latex: "s(t)",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "生存分布",
    definition: "新生儿的生存分布函数：s(t) = P(X > t)",
    formulaLatex: "s(t) = \\exp\\left(-\\int_0^t \\mu(u)\\,du\\right)",
    inputs: [{ name: "t", type: "float", label: "时间" }],
    outputs: [{ name: "value", type: "float", label: "生存概率" }],
    dependencies: ["mu_t"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "de_moivre_mu",
    symbol: "μ(t) = 1/(ω−t)",
    latex: "\\mu(t) = \\frac{1}{\\omega - t}",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "死亡力模型",
    definition: "De Moivre (1729) 死亡力：μ(t) = 1/(ω−t), 0 ≤ t < ω",
    formulaLatex: "\\mu(t) = \\frac{1}{\\omega - t},\\quad 0 \\le t < \\omega",
    inputs: [{ name: "omega", type: "float", label: "极限年龄 ω", default: 100 }],
    outputs: [{ name: "value", type: "float", label: "死亡力" }],
    dependencies: [],
    isLeaf: true,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "gompertz_mu",
    symbol: "μ(t) = B·C^t",
    latex: "\\mu(t) = B \\cdot C^t",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "死亡力模型",
    definition: "Gompertz (1825) 死亡力：μ(t) = B·C^t, B>0, C≥1",
    formulaLatex: "\\mu(t) = B \\cdot C^t,\\quad B > 0,\\; C \\ge 1",
    inputs: [
      { name: "B", type: "float", label: "参数B" },
      { name: "C", type: "float", label: "参数C", default: 1.0, min: 1 },
    ],
    outputs: [{ name: "value", type: "float", label: "死亡力" }],
    dependencies: [],
    isLeaf: true,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "makeham_mu",
    symbol: "μ(t) = A + B·C^t",
    latex: "\\mu(t) = A + B \\cdot C^t",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "死亡力模型",
    definition: "Makeham (1860) 死亡力：μ(t) = A + B·C^t, B>0, A ≥ −B, C>1",
    formulaLatex: "\\mu(t) = A + B \\cdot C^t,\\quad A \\ge -B,\\; B > 0,\\; C > 1",
    inputs: [
      { name: "A", type: "float", label: "参数A" },
      { name: "B", type: "float", label: "参数B" },
      { name: "C", type: "float", label: "参数C", default: 1.0, min: 1 },
    ],
    outputs: [{ name: "value", type: "float", label: "死亡力" }],
    dependencies: ["gompertz_mu"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
    relatedIds: ["gompertz_mu"],
  },
  {
    id: "weibull_mu",
    symbol: "μ(t) = k·t^n",
    latex: "\\mu(t) = k \\cdot t^n",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "死亡力模型",
    definition: "Weibull (1939) 死亡力：μ(t) = k·t^n, k>0, n>0",
    formulaLatex: "\\mu(t) = k \\cdot t^n,\\quad k > 0,\\; n > 0",
    inputs: [
      { name: "k", type: "float", label: "参数k" },
      { name: "n", type: "float", label: "参数n", default: 1.0 },
    ],
    outputs: [{ name: "value", type: "float", label: "死亡力" }],
    dependencies: [],
    isLeaf: true,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "Tx",
    symbol: "T(x)",
    latex: "T(x)",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "未来生存时间",
    definition: "x岁个体的未来生存时间（随机变量）：T(x) = X − x | X > x",
    formulaLatex: "T(x) = X - x \\mid X > x",
    inputs: [{ name: "x", type: "int", label: "当前年龄" }],
    outputs: [{ name: "distribution", type: "distribution", label: "生存时间分布" }],
    dependencies: ["survival_s"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "Kx",
    symbol: "K(x)",
    latex: "K(x)",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "未来生存整年数",
    definition: "x岁个体的未来生存整年数：K(x) = ⌊T(x)⌋",
    formulaLatex: "K(x) = \\lfloor T(x) \\rfloor",
    inputs: [{ name: "x", type: "int", label: "当前年龄" }],
    outputs: [{ name: "value", type: "int", label: "整年数" }],
    dependencies: ["Tx"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "t_px",
    symbol: "_t p_x",
    latex: "{}_t p_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "生存概率",
    definition: "x岁的个体活过x+t岁的概率",
    formulaLatex: "{}_t p_x = \\exp\\left(-\\int_0^t \\mu_{x}(s)\\,ds\\right) = \\frac{l_{x+t}}{l_x}",
    inputs: [
      { name: "t", type: "float", label: "年数" },
      { name: "x", type: "int", label: "当前年龄" },
    ],
    outputs: [{ name: "value", type: "float", label: "生存概率" }],
    dependencies: ["survival_s", "lx"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "t_qx",
    symbol: "_t q_x",
    latex: "{}_t q_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "死亡概率",
    definition: "x岁的个体在x+t岁前死亡的概率",
    formulaLatex: "{}_t q_x = 1 - {}_t p_x = \\frac{{}_t d_x}{l_x}",
    inputs: [
      { name: "t", type: "float", label: "年数" },
      { name: "x", type: "int", label: "当前年龄" },
    ],
    outputs: [{ name: "value", type: "float", label: "死亡概率" }],
    dependencies: ["t_px"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "u_given_t_qx",
    symbol: "_{u|} _t q_x",
    latex: "{}_{u|} {}_t q_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "延期死亡概率",
    definition: "x岁的个体在x+u岁至x+u+t岁之间死亡的概率",
    formulaLatex: "{}_{u|} {}_t q_x = {}_u p_x \\cdot {}_t q_{x+u} = {}_u p_x - {}_{u+t} p_x",
    inputs: [
      { name: "u", type: "float", label: "延期年数" },
      { name: "t", type: "float", label: "死亡区间长度" },
      { name: "x", type: "int", label: "当前年龄" },
    ],
    outputs: [{ name: "value", type: "float", label: "延期死亡概率" }],
    dependencies: ["t_px", "t_qx"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "lx",
    symbol: "l_x",
    latex: "l_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "生命表",
    definition: "生存群中活到x岁的个体数的期望：l_x = l_0 · s(x)",
    formulaLatex: "l_x = l_0 \\cdot s(x) = l_0 \\cdot {}_x p_0",
    inputs: [{ name: "x", type: "int", label: "年龄" }],
    outputs: [{ name: "value", type: "float", label: "生存人数" }],
    dependencies: ["t_px"],
    isLeaf: false,
    variation: "from_life_table",
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "dx",
    symbol: "d_x",
    latex: "d_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "生命表",
    definition: "生存群中在x到x+1岁之间死亡的个体数的期望",
    formulaLatex: "d_x = l_x - l_{x+1} = l_x \\cdot q_x",
    inputs: [{ name: "x", type: "int", label: "年龄" }],
    outputs: [{ name: "value", type: "float", label: "死亡人数" }],
    dependencies: ["lx", "qx"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "complete_ex",
    symbol: "ė_x",
    latex: "\\mathring{e}_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "平均余命",
    definition: "x岁个体的完全平均余命（未来生存时间的期望）",
    formulaLatex: "\\mathring{e}_x = E[T(x)] = \\int_0^{\\infty} {}_t p_x \\, dt",
    inputs: [{ name: "x", type: "int", label: "当前年龄" }],
    outputs: [{ name: "value", type: "float", label: "完全平均余命" }],
    dependencies: ["t_px"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "curtate_ex",
    symbol: "e_x",
    latex: "e_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "平均余命",
    definition: "x岁个体的整年平均余命：e_x = E[K(x)]",
    formulaLatex: "e_x = E[K(x)] = \\sum_{k=1}^{\\infty} {}_k p_x",
    inputs: [{ name: "x", type: "int", label: "当前年龄" }],
    outputs: [{ name: "value", type: "float", label: "整年平均余命" }],
    dependencies: ["t_px"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "mu_x_t",
    symbol: "μ_x(t)",
    latex: "\\mu_x(t)",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "死亡力",
    definition: "x岁个体的死亡力函数：μ_x(t) = μ(x+t)",
    formulaLatex: "\\mu_x(t) = \\mu(x+t) = -\\frac{d}{dt}\\ln({}_t p_x)",
    inputs: [
      { name: "t", type: "float", label: "时间偏移" },
      { name: "x", type: "int", label: "当前年龄" },
    ],
    outputs: [{ name: "value", type: "float", label: "死亡力" }],
    dependencies: ["t_px"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "n_mx",
    symbol: "_n m_x",
    latex: "{}_n m_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "中心死亡率",
    definition: "中心死亡率：_n m_x = _n q_x / ∫_0^n _t p_x dt",
    formulaLatex: "{}_n m_x = \\frac{{}_n q_x}{\\int_0^n {}_t p_x \\, dt} = \\frac{{}_n d_x}{{}_n L_x}",
    inputs: [
      { name: "n", type: "int", label: "区间长度" },
      { name: "x", type: "int", label: "当前年龄" },
    ],
    outputs: [{ name: "value", type: "float", label: "中心死亡率" }],
    dependencies: ["t_px", "t_qx", "lx", "dx"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "Tx_life",
    symbol: "T_x",
    latex: "T_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "生命表",
    definition: "生存群中x岁个体总的未来生存时间的期望：T_x = ∫_0^∞ l_{x+s} ds",
    formulaLatex: "T_x = \\int_0^{\\infty} l_{x+s}\\,ds = l_x \\cdot \\mathring{e}_x",
    inputs: [{ name: "x", type: "int", label: "年龄" }],
    outputs: [{ name: "value", type: "float", label: "总生存时间" }],
    dependencies: ["lx", "complete_ex"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "Lx",
    symbol: "L_x",
    latex: "L_x",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "生命表",
    definition: "生存群中x岁个体在[x, x+1)内总生存时间的期望",
    formulaLatex: "L_x = \\int_0^1 l_{x+s}\\,ds = a(x)l_x + (1-a(x))l_{x+1}",
    inputs: [{ name: "x", type: "int", label: "年龄" }],
    outputs: [{ name: "value", type: "float", label: "年生存时间" }],
    dependencies: ["lx"],
    isLeaf: false,
    sourceFile: "chapter1_clean.md",
  },
  {
    id: "udd_assumption",
    symbol: "UDD",
    latex: "\\text{UDD}",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "分数年龄假设",
    definition: "死亡均匀分布假设（UDD）：s(x+t) = (1−t)s(x) + t·s(x+1), 0≤t<1。在此假设下 K(x)⟂S(x), S(x)∼U(0,1)",
    formulaLatex: "{}_t q_x = t \\cdot q_x,\\quad \\mu_x(t) = \\frac{q_x}{1 - t \\cdot q_x},\\quad \\mathring{e}_x = e_x + \\tfrac{1}{2}",
    inputs: [],
    outputs: [],
    dependencies: ["t_qx", "mu_x_t", "complete_ex", "curtate_ex"],
    isLeaf: true,
    sourceFile: "chapter1_clean.md",
    relatedIds: ["constant_force", "balducci"],
  },
  {
    id: "constant_force",
    symbol: "常数死亡力",
    latex: "\\text{常数死亡力}",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "分数年龄假设",
    definition: "常数死亡力假设：死亡力在[x, x+1)内为常数 μ = −ln(1−q_x)",
    formulaLatex: "{}_t q_x = 1 - p_x^{t},\\quad l_{x+t} = l_x e^{-\\mu t},\\quad f_{T(x)}(t) = -p_x^t \\ln p_x",
    inputs: [],
    outputs: [],
    dependencies: ["t_qx", "lx"],
    isLeaf: true,
    sourceFile: "chapter1_clean.md",
    relatedIds: ["udd_assumption", "balducci"],
  },
  {
    id: "balducci",
    symbol: "Balducci",
    latex: "\\text{Balducci}",
    category: "生存分布与生命表",
    chapter: 1,
    subcategory: "分数年龄假设",
    definition: "Balducci假设：1/s(x+t) = (1−t)/s(x) + t/s(x+1)",
    formulaLatex: "{}_t q_x = \\frac{t \\cdot q_x}{1 - (1-t)q_x},\\quad \\mu(x+t) = \\frac{q_x}{1 - (1-t)q_x}",
    inputs: [],
    outputs: [],
    dependencies: ["t_qx", "mu_x_t", "survival_s"],
    isLeaf: true,
    sourceFile: "chapter1_clean.md",
    relatedIds: ["udd_assumption", "constant_force"],
  },
];

// ================================================================
// 第四章：保险现值 (chapter4_clean.md)
// ================================================================

const CH4_FORMULAS: FormulaEntry[] = [
  // ═══ 生存保险 ═══
  {
    id: "pure_endowment",
    symbol: "_n E_x",
    latex: "{}_n E_x",
    category: "保险现值",
    chapter: 4,
    subcategory: "生存保险",
    definition: "n年期生存保险的精算现值（单位保额，被保险人生存至期满时给付）",
    formulaLatex: "{}_n E_x = v^n \\cdot {}_n p_x = \\frac{v^{n} l_{x+n}}{l_x}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["t_px"],
    isLeaf: false,
    sourceFile: "chapter4_clean.md",
    relatedIds: ["Ax_term_discrete", "endowment_insurance_discrete"],
  },
  // ═══ 定期寿险：死亡后立即给付 ═══
  {
    id: "Ax_term_continuous",
    symbol: "Ā^1_{x:n}",
    latex: "\\overline{A}_{x:\\enclose{actuarial}{n}}^1",
    category: "保险现值",
    chapter: 4,
    subcategory: "定期寿险",
    definition: "n年期死亡保险的精算现值（保额在个体死亡后立即给付）",
    formulaLatex: "\\overline{A}_{x:\\enclose{actuarial}{n}}^1 = \\int_0^n v^t \\cdot {}_t p_x \\cdot \\mu_x(t)\\,dt",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["t_px", "mu_x_t"],
    isLeaf: false,
    variation: "continuous",
    sourceFile: "chapter4_clean.md",
    relatedIds: ["Ax_term_discrete"],
  },
  // ═══ 定期寿险：死亡保单年度末给付 ═══
  {
    id: "Ax_term_discrete",
    symbol: "A^1_{x:n}",
    latex: "A_{x:\\enclose{actuarial}{n}}^1",
    category: "保险现值",
    chapter: 4,
    subcategory: "定期寿险",
    definition: "n年期死亡保险的精算现值（保额在个体死亡的保单年度末给付）",
    formulaLatex: "A_{x:\\enclose{actuarial}{n}}^1 = \\sum_{k=0}^{n-1} v^{k+1} \\cdot {}_k p_x \\cdot q_{x+k}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["t_px", "t_qx"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter4_clean.md",
    relatedIds: ["Ax_term_continuous", "Ax_discrete"],
  },
  // ═══ 终身寿险：死亡后立即给付 ═══
  {
    id: "Ax_continuous",
    symbol: "Ā_x",
    latex: "\\overline{A}_x",
    category: "保险现值",
    chapter: 4,
    subcategory: "终身寿险",
    definition: "终身寿险的精算现值（保额在个体死亡后立即给付）",
    formulaLatex: "\\overline{A}_x = \\int_0^{\\infty} v^t \\cdot {}_t p_x \\cdot \\mu_x(t)\\,dt",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["t_px", "mu_x_t"],
    isLeaf: false,
    variation: "continuous",
    sourceFile: "chapter4_clean.md",
    relatedIds: ["Ax_discrete", "Ax_term_continuous"],
  },
  // ═══ 终身寿险：死亡保单年度末给付 ═══
  {
    id: "Ax_discrete",
    symbol: "A_x",
    latex: "A_x",
    category: "保险现值",
    chapter: 4,
    subcategory: "终身寿险",
    definition: "终身寿险的精算现值（保额在个体死亡的保单年度末给付）",
    formulaLatex: "A_x = \\sum_{k=0}^{\\infty} v^{k+1} \\cdot {}_k p_x \\cdot q_{x+k}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["t_px", "t_qx"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter4_clean.md",
    relatedIds: ["Ax_continuous", "Ax_term_discrete", "deferred_Ax_discrete"],
  },
  // ═══ 生死合险 ═══
  {
    id: "endowment_insurance_continuous",
    symbol: "Ā_{x:n}",
    latex: "\\overline{A}_{x:\\enclose{actuarial}{n}}",
    category: "保险现值",
    chapter: 4,
    subcategory: "生死合险",
    definition: "n年期生死合险的精算现值（死亡后立即给付或期满生存给付）",
    formulaLatex: "\\overline{A}_{x:\\enclose{actuarial}{n}} = \\overline{A}_{x:\\enclose{actuarial}{n}}^1 + {}_n E_x",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["Ax_term_continuous", "pure_endowment"],
    isLeaf: false,
    variation: "continuous",
    sourceFile: "chapter4_clean.md",
    relatedIds: ["endowment_insurance_discrete"],
  },
  {
    id: "endowment_insurance_discrete",
    symbol: "A_{x:n}",
    latex: "A_{x:\\enclose{actuarial}{n}}",
    category: "保险现值",
    chapter: 4,
    subcategory: "生死合险",
    definition: "n年期生死合险的精算现值（死亡保单年度末给付或期满生存给付）",
    formulaLatex: "A_{x:\\enclose{actuarial}{n}} = A_{x:\\enclose{actuarial}{n}}^1 + {}_n E_x",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["Ax_term_discrete", "pure_endowment"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter4_clean.md",
    relatedIds: ["endowment_insurance_continuous"],
  },
  // ═══ 延期保险 ═══
  {
    id: "deferred_Ax_continuous",
    symbol: "_m|Ā_x",
    latex: "{}_{m|}\\overline{A}_x",
    category: "保险现值",
    chapter: 4,
    subcategory: "延期保险",
    definition: "延期m年终身寿险的精算现值（死亡后立即给付）",
    formulaLatex: "{}_{m|}\\overline{A}_x = \\int_m^{\\infty} v^t \\cdot {}_t p_x \\cdot \\mu_x(t)\\,dt = {}_m E_x \\cdot \\overline{A}_{x+m}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "m", type: "int", label: "延期年数" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["pure_endowment", "Ax_continuous"],
    isLeaf: false,
    variation: "continuous",
    sourceFile: "chapter4_clean.md",
    relatedIds: ["deferred_Ax_discrete"],
  },
  {
    id: "deferred_Ax_discrete",
    symbol: "_m|A_x",
    latex: "{}_{m|}A_x",
    category: "保险现值",
    chapter: 4,
    subcategory: "延期保险",
    definition: "延期m年终身寿险的精算现值（死亡保单年度末给付）",
    formulaLatex: "{}_{m|}A_x = \\sum_{k=m}^{\\infty} v^{k+1} \\cdot {}_{k|}q_x = {}_m E_x \\cdot A_{x+m}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "m", type: "int", label: "延期年数" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["pure_endowment", "Ax_discrete"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter4_clean.md",
    relatedIds: ["deferred_Ax_continuous"],
  },
  // ═══ 递增/递减保险 ═══
  {
    id: "increasing_IAx",
    symbol: "(IĀ)_x",
    latex: "(\\overline{I}\\overline{A})_x",
    category: "保险现值",
    chapter: 4,
    subcategory: "变额保险",
    definition: "标准年递增终身寿险精算现值（死亡后立即给付），第k+1年死亡给付k+1元",
    formulaLatex: "(\\overline{IA})_x = \\int_0^{\\infty} \\lceil t \\rceil \\cdot v^t \\cdot {}_t p_x \\cdot \\mu_x(t)\\,dt",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["t_px", "mu_x_t"],
    isLeaf: false,
    sourceFile: "chapter4_clean.md",
  },
  {
    id: "increasing_IAx_discrete",
    symbol: "(IA)_x",
    latex: "(IA)_x",
    category: "保险现值",
    chapter: 4,
    subcategory: "变额保险",
    definition: "标准年递增终身寿险精算现值（死亡保单年度末给付）",
    formulaLatex: "(IA)_x = \\sum_{k=0}^{\\infty} (k+1) \\cdot v^{k+1} \\cdot {}_k p_x \\cdot q_{x+k}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["t_px", "t_qx"],
    isLeaf: false,
    sourceFile: "chapter4_clean.md",
  },
  {
    id: "decreasing_DAx_discrete",
    symbol: "(DA)^1_{x:n}",
    latex: "(DA)_{x:\\enclose{actuarial}{n}}^1",
    category: "保险现值",
    chapter: 4,
    subcategory: "变额保险",
    definition: "标准年递减n年期寿险精算现值（死亡保单年度末给付），第k+1年死亡给付n−k元",
    formulaLatex: "(DA)_{x:\\enclose{actuarial}{n}}^1 = \\sum_{k=0}^{n-1} (n-k) \\cdot v^{k+1} \\cdot {}_k p_x \\cdot q_{x+k}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算现值" }],
    dependencies: ["t_px", "t_qx", "Ax_term_discrete"],
    isLeaf: false,
    sourceFile: "chapter4_clean.md",
  },
  // ═══ UDD 关系 ═══
  {
    id: "udd_ax_ax_relation",
    symbol: "Ā = (i/δ)·A",
    latex: "\\overline{A} = \\frac{i}{\\delta} A",
    category: "保险现值",
    chapter: 4,
    subcategory: "UDD关系",
    definition: "在UDD假设下，连续与离散精算现值的关系：Ā = (i/δ)·A（定理4.9.1）",
    formulaLatex: "\\overline{A}_{x:\\enclose{actuarial}{n}}^1 = \\frac{i}{\\delta} \\cdot A_{x:\\enclose{actuarial}{n}}^1",
    inputs: [{ name: "i", type: "float", label: "利率" }],
    outputs: [],
    dependencies: ["Ax_continuous", "Ax_discrete"],
    isLeaf: false,
    sourceFile: "chapter4_clean.md",
  },
];

// ================================================================
// 第五章：年金现值 (chapter5_clean.md)
// ================================================================

const CH5_FORMULAS: FormulaEntry[] = [
  // ═══ 连续年金 ═══
  {
    id: "ax_continuous",
    symbol: "ā_x",
    latex: "\\overline{a}_x",
    category: "年金现值",
    chapter: 5,
    subcategory: "连续年金",
    definition: "给付率为1的连续终身生存年金的精算现值",
    formulaLatex: "\\overline{a}_x = \\int_0^{\\infty} v^t \\cdot {}_t p_x \\, dt",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年金现值" }],
    dependencies: ["t_px"],
    isLeaf: false,
    variation: "continuous",
    sourceFile: "chapter5_clean.md",
  },
  {
    id: "ax_term_continuous",
    symbol: "ā_{x:n}",
    latex: "\\overline{a}_{x:\\enclose{actuarial}{n}}",
    category: "年金现值",
    chapter: 5,
    subcategory: "连续年金",
    definition: "给付率为1的n年期连续生存年金的精算现值",
    formulaLatex: "\\overline{a}_{x:\\enclose{actuarial}{n}} = \\int_0^n v^t \\cdot {}_t p_x \\, dt",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "年金期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年金现值" }],
    dependencies: ["t_px"],
    isLeaf: false,
    variation: "continuous",
    sourceFile: "chapter5_clean.md",
  },
  // ═══ 期初年金 ═══
  {
    id: "ax_due_discrete",
    symbol: "ä_x",
    latex: "\\ddot{a}_x",
    category: "年金现值",
    chapter: 5,
    subcategory: "期初年金",
    definition: "每年年初给付一个单位的终身生存年金的精算现值",
    formulaLatex: "\\ddot{a}_x = \\sum_{k=0}^{\\infty} v^k \\cdot {}_k p_x",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年金现值" }],
    dependencies: ["t_px"],
    isLeaf: false,
    variation: "due",
    sourceFile: "chapter5_clean.md",
    relatedIds: ["ax_immediate_discrete", "ax_continuous"],
  },
  {
    id: "ax_term_due_discrete",
    symbol: "ä_{x:n}",
    latex: "\\ddot{a}_{x:\\enclose{actuarial}{n}}",
    category: "年金现值",
    chapter: 5,
    subcategory: "期初年金",
    definition: "每年年初给付一个单位的n年期生存年金的精算现值",
    formulaLatex: "\\ddot{a}_{x:\\enclose{actuarial}{n}} = \\sum_{k=0}^{n-1} v^k \\cdot {}_k p_x",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "年金期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年金现值" }],
    dependencies: ["t_px"],
    isLeaf: false,
    variation: "due",
    sourceFile: "chapter5_clean.md",
  },
  // ═══ 期末年金 ═══
  {
    id: "ax_immediate_discrete",
    symbol: "a_x",
    latex: "a_x",
    category: "年金现值",
    chapter: 5,
    subcategory: "期末年金",
    definition: "每年年末给付一个单位的终身生存年金的精算现值",
    formulaLatex: "a_x = \\ddot{a}_x - 1 = \\sum_{k=1}^{\\infty} v^k \\cdot {}_k p_x",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年金现值" }],
    dependencies: ["ax_due_discrete"],
    isLeaf: false,
    variation: "immediate",
    sourceFile: "chapter5_clean.md",
  },
  // ═══ 延期年金 ═══
  {
    id: "deferred_ax_continuous",
    symbol: "_n|ā_x",
    latex: "{}_{n|}\\overline{a}_x",
    category: "年金现值",
    chapter: 5,
    subcategory: "延期年金",
    definition: "给付率为1的延期n年的连续终身生存年金的精算现值",
    formulaLatex: "{}_{n|}\\overline{a}_x = \\int_n^{\\infty} v^t \\cdot {}_t p_x \\, dt = {}_n E_x \\cdot \\overline{a}_{x+n}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "延期年数" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年金现值" }],
    dependencies: ["pure_endowment", "ax_continuous"],
    isLeaf: false,
    sourceFile: "chapter5_clean.md",
  },
  {
    id: "deferred_ax_due_discrete",
    symbol: "_n|ä_x",
    latex: "{}_{n|}\\ddot{a}_x",
    category: "年金现值",
    chapter: 5,
    subcategory: "延期年金",
    definition: "每年年初给付一个单位的延期n年的终身生存年金的精算现值",
    formulaLatex: "{}_{n|}\\ddot{a}_x = v^n \\cdot {}_n p_x \\cdot \\ddot{a}_{x+n} = {}_n E_x \\cdot \\ddot{a}_{x+n}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "延期年数" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年金现值" }],
    dependencies: ["pure_endowment", "ax_due_discrete"],
    isLeaf: false,
    sourceFile: "chapter5_clean.md",
  },
  // ═══ 确定期年金 ═══
  {
    id: "certain_and_life_ax_due",
    symbol: "ä_{x:n̄}",
    latex: "\\ddot{a}_{\\overline{x:\\enclose{actuarial}{n}}}",
    category: "年金现值",
    chapter: 5,
    subcategory: "确定期年金",
    definition: "n年确定期终身生存年金：前n年确定给付+之后生存给付",
    formulaLatex: "\\ddot{a}_{\\overline{x:\\enclose{actuarial}{n}}} = \\ddot{a}_{\\overline{n|}} + {}_{n|}\\ddot{a}_x",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "确定期（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年金现值" }],
    dependencies: ["deferred_ax_due_discrete"],
    isLeaf: false,
    sourceFile: "chapter5_clean.md",
  },
  // ═══ 核心恒等式 ═══
  {
    id: "insurance_annuity_identity_cont",
    symbol: "δā_x + Ā_x = 1",
    latex: "\\delta\\overline{a}_x + \\overline{A}_x = 1",
    category: "年金现值",
    chapter: 5,
    subcategory: "恒等式",
    definition: "连续情况下的保险-年金恒等式：利息给付+本金返还=投资额",
    formulaLatex: "\\delta \\cdot \\overline{a}_x + \\overline{A}_x = 1",
    inputs: [{ name: "i", type: "float", label: "利率", default: 0.035 }],
    outputs: [],
    dependencies: ["ax_continuous", "Ax_continuous"],
    isLeaf: false,
    sourceFile: "chapter5_clean.md",
  },
  {
    id: "insurance_annuity_identity_disc",
    symbol: "dä_x + A_x = 1",
    latex: "d\\ddot{a}_x + A_x = 1",
    category: "年金现值",
    chapter: 5,
    subcategory: "恒等式",
    definition: "离散情况下的保险-年金恒等式：利息给付+本金返还=投资额",
    formulaLatex: "d \\cdot \\ddot{a}_x + A_x = 1",
    inputs: [{ name: "i", type: "float", label: "利率", default: 0.035 }],
    outputs: [],
    dependencies: ["ax_due_discrete", "Ax_discrete"],
    isLeaf: false,
    sourceFile: "chapter5_clean.md",
  },
  // ═══ 精算终值 ═══
  {
    id: "actuarial_accumulation",
    symbol: "s̈_{x:n}",
    latex: "\\ddot{s}_{x:\\enclose{actuarial}{n}}",
    category: "年金现值",
    chapter: 5,
    subcategory: "精算终值",
    definition: "n年期期初生存年金的精算终值：s̈_{x:n} = ä_{x:n} / _nE_x",
    formulaLatex: "\\ddot{s}_{x:\\enclose{actuarial}{n}} = \\frac{\\ddot{a}_{x:\\enclose{actuarial}{n}}}{{}_n E_x}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "精算终值" }],
    dependencies: ["ax_term_due_discrete", "pure_endowment"],
    isLeaf: false,
    sourceFile: "chapter5_clean.md",
  },
];

// ================================================================
// 第八章：净保费理论 (chapter8_clean.md)
// ================================================================

const CH8_FORMULAS: FormulaEntry[] = [
  {
    id: "Px_continuous",
    symbol: "P̄(Ā_x)",
    latex: "\\overline{P}(\\overline{A}_x)",
    category: "净保费理论",
    chapter: 8,
    subcategory: "完全连续",
    definition: "完全连续终身寿险的年均衡净保费缴纳率",
    formulaLatex: "\\overline{P}(\\overline{A}_x) = \\frac{\\overline{A}_x}{\\overline{a}_x} = \\frac{1}{\\overline{a}_x} - \\delta = \\frac{\\delta\\overline{A}_x}{1-\\overline{A}_x}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年均衡净保费率" }],
    dependencies: ["Ax_continuous", "ax_continuous"],
    isLeaf: false,
    variation: "continuous",
    sourceFile: "chapter8_clean.md",
  },
  {
    id: "Px_term_continuous",
    symbol: "P̄(Ā^1_{x:n})",
    latex: "\\overline{P}(\\overline{A}_{x:\\enclose{actuarial}{n}}^1)",
    category: "净保费理论",
    chapter: 8,
    subcategory: "完全连续",
    definition: "完全连续n年期寿险的年均衡净保费缴纳率",
    formulaLatex: "\\overline{P}(\\overline{A}_{x:\\enclose{actuarial}{n}}^1) = \\frac{\\overline{A}_{x:\\enclose{actuarial}{n}}^1}{\\overline{a}_{x:\\enclose{actuarial}{n}}}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年均衡净保费率" }],
    dependencies: ["Ax_term_continuous", "ax_term_continuous"],
    isLeaf: false,
    variation: "continuous",
    sourceFile: "chapter8_clean.md",
  },
  {
    id: "Px_discrete",
    symbol: "P_x",
    latex: "P_x",
    category: "净保费理论",
    chapter: 8,
    subcategory: "完全离散",
    definition: "完全离散终身寿险的年均衡净保费",
    formulaLatex: "P_x = \\frac{A_x}{\\ddot{a}_x} = \\frac{1}{\\ddot{a}_x} - d = \\frac{dA_x}{1-A_x}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年均衡净保费" }],
    dependencies: ["Ax_discrete", "ax_due_discrete"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter8_clean.md",
  },
  {
    id: "Px_term_discrete",
    symbol: "P^1_{x:n}",
    latex: "P_{x:\\enclose{actuarial}{n}}^1",
    category: "净保费理论",
    chapter: 8,
    subcategory: "完全离散",
    definition: "完全离散n年期寿险的年均衡净保费",
    formulaLatex: "P_{x:\\enclose{actuarial}{n}}^1 = \\frac{A_{x:\\enclose{actuarial}{n}}^1}{\\ddot{a}_{x:\\enclose{actuarial}{n}}}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年均衡净保费" }],
    dependencies: ["Ax_term_discrete", "ax_term_due_discrete"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter8_clean.md",
  },
  {
    id: "Px_endowment_discrete",
    symbol: "P_{x:n}",
    latex: "P_{x:\\enclose{actuarial}{n}}",
    category: "净保费理论",
    chapter: 8,
    subcategory: "完全离散",
    definition: "完全离散n年期生死合险的年均衡净保费",
    formulaLatex: "P_{x:\\enclose{actuarial}{n}} = \\frac{A_{x:\\enclose{actuarial}{n}}}{\\ddot{a}_{x:\\enclose{actuarial}{n}}}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年均衡净保费" }],
    dependencies: ["endowment_insurance_discrete", "ax_term_due_discrete"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter8_clean.md",
  },
  {
    id: "h_pay_Px_discrete",
    symbol: "_h P_x",
    latex: "{}_h P_x",
    category: "净保费理论",
    chapter: 8,
    subcategory: "限期缴费",
    definition: "h年限期缴费终身寿险的年均衡净保费",
    formulaLatex: "{}_h P_x = \\frac{A_x}{\\ddot{a}_{x:\\enclose{actuarial}{h}}}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "h", type: "int", label: "缴费期（年）" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年均衡净保费" }],
    dependencies: ["Ax_discrete", "ax_term_due_discrete"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter8_clean.md",
  },
  {
    id: "Px_semi_continuous",
    symbol: "P(Ā_x)",
    latex: "P(\\overline{A}_x)",
    category: "净保费理论",
    chapter: 8,
    subcategory: "半连续",
    definition: "半连续终身寿险的年均衡净保费（保费离散缴纳，保额即时给付）",
    formulaLatex: "P(\\overline{A}_x) = \\frac{\\overline{A}_x}{\\ddot{a}_x} = \\frac{i}{\\delta} \\cdot P_x \\quad \\text{(UDD下)}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "年均衡净保费" }],
    dependencies: ["Ax_continuous", "ax_due_discrete"],
    isLeaf: false,
    variation: "semi-continuous",
    sourceFile: "chapter8_clean.md",
  },
  {
    id: "loss_variance_continuous",
    symbol: "Var(L)",
    latex: "\\text{Var}(L)",
    category: "净保费理论",
    chapter: 8,
    subcategory: "签单损失",
    definition: "完全连续险种签单损失量的方差",
    formulaLatex: "\\text{Var}(L) = \\frac{{}^2\\overline{A}_{x} - (\\overline{A}_x)^2}{(\\delta \\cdot \\overline{a}_x)^2}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "方差" }],
    dependencies: ["Ax_continuous", "ax_continuous"],
    isLeaf: false,
    sourceFile: "chapter8_clean.md",
  },
];

// ================================================================
// 第十章：净准备金一般理论 (chapter10_clean.md)
// ================================================================

const CH10_FORMULAS: FormulaEntry[] = [
  {
    id: "Ch",
    symbol: "C_h",
    latex: "C_h",
    category: "净准备金（一般理论）",
    chapter: 10,
    subcategory: "资金损失",
    definition: "保险人在第h+1个保单年度的资金损失的现值（不考虑准备金变化）",
    formulaLatex: "C_h = v \\cdot b_{h+1} \\cdot I\\{K(x)=h\\} - \\pi_h \\cdot I\\{K(x) \\ge h\\}",
    inputs: [
      { name: "h", type: "int", label: "保单年度" },
      { name: "b", type: "float", label: "保险金" },
      { name: "pi", type: "float", label: "保费" },
    ],
    outputs: [{ name: "expectation", type: "float", label: "期望(C_h)" }],
    dependencies: ["t_px", "t_qx"],
    isLeaf: false,
    sourceFile: "chapter10_clean.md",
  },
  {
    id: "hV",
    symbol: "_h V",
    latex: "{}_h V",
    category: "净准备金（一般理论）",
    chapter: 10,
    subcategory: "净准备金",
    definition: "保险人在第h+1个保单年度末的净准备金（将来法）",
    formulaLatex: "{}_h V = \\sum_{j=0}^{\\infty} b_{h+j+1} v^{j+1} {}_{j|}q_{x+h} - \\sum_{j=0}^{\\infty} \\pi_{h+j} v^j {}_j p_{x+h}",
    inputs: [
      { name: "h", type: "int", label: "保单年度" },
      { name: "x", type: "int", label: "签约年龄" },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["t_px", "t_qx", "Ax_discrete", "ax_due_discrete"],
    isLeaf: false,
    sourceFile: "chapter10_clean.md",
  },
  {
    id: "Lambda_h",
    symbol: "Λ_h",
    latex: "\\Lambda_h",
    category: "净准备金（一般理论）",
    chapter: 10,
    subcategory: "资金变化",
    definition: "考虑净准备金变化时，保险人在第h+1个保单年度的资金损失现值",
    formulaLatex: "\\Lambda_h = v(b_{h+1} - {}_{h+1}V)I\\{K(x)=h\\} - (\\pi_h + {}_h V - v\\cdot{}_{h+1}V)I\\{K(x)\\ge h\\}",
    inputs: [
      { name: "h", type: "int", label: "保单年度" },
    ],
    outputs: [{ name: "variance", type: "float", label: "Var(Λ_h|K≥h)" }],
    dependencies: ["hV", "Ch"],
    isLeaf: false,
    sourceFile: "chapter10_clean.md",
  },
  {
    id: "reserve_recursion",
    symbol: "递推公式",
    latex: "{}_h V + \\pi_h = v b_{h+1} q_{x+h} + v \\cdot {}_{h+1}V \\cdot p_{x+h}",
    category: "净准备金（一般理论）",
    chapter: 10,
    subcategory: "递推公式",
    definition: "净准备金的递推关系（定理10.3.2）",
    formulaLatex: "{}_h V = v b_{h+1} q_{x+h} - \\pi_h + v \\cdot {}_{h+1}V \\cdot p_{x+h}",
    inputs: [
      { name: "h", type: "int", label: "保单年度" },
    ],
    outputs: [],
    dependencies: ["hV", "t_px", "t_qx"],
    isLeaf: false,
    sourceFile: "chapter10_clean.md",
  },
  {
    id: "hattendorf",
    symbol: "Hattendorf",
    latex: "\\text{Hattendorf 定理}",
    category: "净准备金（一般理论）",
    chapter: 10,
    subcategory: "方差分解",
    definition: "Hattendorf定理：未来损失量方差 = 各年Λ_h方差之和（定理10.5.1）",
    formulaLatex: "\\text{Var}[{}_h L|K\\ge h] = \\sum_{j=h}^{\\infty} v^{2(j-h)} [v(b_{j+1}-{}_{j+1}V)]^2 {}_{j-h}p_{x+h} p_{x+j} q_{x+j}",
    inputs: [
      { name: "h", type: "int", label: "保单年度" },
    ],
    outputs: [{ name: "value", type: "float", label: "方差" }],
    dependencies: ["hV", "Lambda_h", "t_px", "t_qx"],
    isLeaf: false,
    sourceFile: "chapter10_clean.md",
  },
];

// ================================================================
// 第十一章：完全离散净准备金 (chapter11_clean.md)
// ================================================================

const CH11_FORMULAS: FormulaEntry[] = [
  {
    id: "kVx_discrete",
    symbol: "_k V_x",
    latex: "{}_k V_x",
    category: "净准备金（完全离散）",
    chapter: 11,
    subcategory: "终身寿险",
    definition: "完全离散终身寿险第k+1保单年度末的净准备金（将来法）",
    formulaLatex: "{}_k V_x = A_{x+k} - P_x \\cdot \\ddot{a}_{x+k}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "k", type: "int", label: "保单年度" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["Ax_discrete", "ax_due_discrete", "Px_discrete"],
    isLeaf: false,
    variation: "discrete",
    sourceFile: "chapter11_clean.md",
  },
  {
    id: "kVx_premium_diff",
    symbol: "_k V_x = (P_{x+k}−P_x)ä_{x+k}",
    latex: "{}_k V_x = (P_{x+k} - P_x)\\ddot{a}_{x+k}",
    category: "净准备金（完全离散）",
    chapter: 11,
    subcategory: "保费差公式",
    definition: "保费差公式：准备金 = (x+k岁签单的保费 − x岁签单的保费) × 年金现值",
    formulaLatex: "{}_k V_x = (P_{x+k} - P_x) \\cdot \\ddot{a}_{x+k}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "k", type: "int", label: "保单年度" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["kVx_discrete", "Px_discrete", "ax_due_discrete"],
    isLeaf: false,
    sourceFile: "chapter11_clean.md",
    relatedIds: ["kVx_paidup", "kVx_retrospective"],
  },
  {
    id: "kVx_paidup",
    symbol: "_k V_x = (1−P_x/P_{x+k})A_{x+k}",
    latex: "{}_k V_x = \\left(1 - \\frac{P_x}{P_{x+k}}\\right) A_{x+k}",
    category: "净准备金（完全离散）",
    chapter: 11,
    subcategory: "缴清保险公式",
    definition: "缴清保险公式：准备金占未来保额的比重 = 已缴保费占比的补集",
    formulaLatex: "{}_k V_x = \\left(1 - \\frac{P_x}{P_{x+k}}\\right) \\cdot A_{x+k}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "k", type: "int", label: "保单年度" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["kVx_discrete", "Px_discrete", "Ax_discrete"],
    isLeaf: false,
    sourceFile: "chapter11_clean.md",
    relatedIds: ["kVx_premium_diff", "kVx_retrospective"],
  },
  {
    id: "kVx_retrospective",
    symbol: "_k V_x = P_x·s̈ − _kκ_x",
    latex: "{}_k V_x = P_x \\cdot \\ddot{s}_{x:\\enclose{actuarial}{k}} - {}_k \\kappa_x",
    category: "净准备金（完全离散）",
    chapter: 11,
    subcategory: "过去法",
    definition: "过去法公式：准备金 = 已缴保费累积 − 精算累计成本",
    formulaLatex: "{}_k V_x = P_x \\cdot \\ddot{s}_{x:\\enclose{actuarial}{k}} - {}_k \\kappa_x,\\quad {}_k \\kappa_x = \\frac{A_{x:\\enclose{actuarial}{k}}^1}{{}_k E_x}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "k", type: "int", label: "保单年度" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["Px_discrete", "actuarial_accumulation", "Ax_term_discrete", "pure_endowment"],
    isLeaf: false,
    sourceFile: "chapter11_clean.md",
    relatedIds: ["kVx_premium_diff", "kVx_paidup"],
  },
  {
    id: "kVx_endowment_discrete",
    symbol: "_k V_{x:n}",
    latex: "{}_k V_{x:\\enclose{actuarial}{n}}",
    category: "净准备金（完全离散）",
    chapter: 11,
    subcategory: "生死合险",
    definition: "完全离散n年期生死合险的净准备金",
    formulaLatex: "{}_k V_{x:\\enclose{actuarial}{n}} = A_{x+k:\\enclose{actuarial}{n-k}} - P_{x:\\enclose{actuarial}{n}} \\cdot \\ddot{a}_{x+k:\\enclose{actuarial}{n-k}}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "n", type: "int", label: "保险期间（年）" },
      { name: "k", type: "int", label: "保单年度" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["endowment_insurance_discrete", "ax_term_due_discrete", "Px_endowment_discrete"],
    isLeaf: false,
    sourceFile: "chapter11_clean.md",
  },
  {
    id: "fackler_recursion",
    symbol: "Fackler递推",
    latex: "{}_{k+1}V_x = \\frac{({}_k V_x + P_x)(1+i) - q_{x+k}}{p_{x+k}}",
    category: "净准备金（完全离散）",
    chapter: 11,
    subcategory: "递推公式",
    definition: "Fackler递推公式：从_kV计算_{k+1}V的递推关系",
    formulaLatex: "{}_{k+1}V_x = \\frac{({}_k V_x + P_x)(1+i) - q_{x+k}}{p_{x+k}},\\quad {}_0 V_x = 0",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "k", type: "int", label: "当前保单年度" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "_{k+1}V" }],
    dependencies: ["kVx_discrete", "Px_discrete", "t_px", "t_qx"],
    isLeaf: false,
    sourceFile: "chapter11_clean.md",
  },
];

// ================================================================
// 第十二章：完全连续净准备金 (chapter12_clean.md)
// ================================================================

const CH12_FORMULAS: FormulaEntry[] = [
  {
    id: "tV_continuous",
    symbol: "_t V̄",
    latex: "{}_t \\overline{V}",
    category: "净准备金（完全连续）",
    chapter: 12,
    subcategory: "将来法",
    definition: "完全连续险种在时刻t的净准备金",
    formulaLatex: "{}_t \\overline{V} = \\int_0^{\\infty} [b_{t+s}\\mu_x(t+s) - \\pi_{t+s}] v^s {}_s p_{x+t}\\,ds",
    inputs: [
      { name: "t", type: "float", label: "时刻" },
      { name: "x", type: "int", label: "签约年龄" },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["t_px", "mu_x_t"],
    isLeaf: false,
    sourceFile: "chapter12_clean.md",
  },
  {
    id: "tV_ax_continuous",
    symbol: "_t V̄(Ā_x)",
    latex: "{}_t \\overline{V}(\\overline{A}_x)",
    category: "净准备金（完全连续）",
    chapter: 12,
    subcategory: "终身寿险",
    definition: "完全连续终身寿险在时刻t的净准备金（将来法）",
    formulaLatex: "{}_t \\overline{V}(\\overline{A}_x) = \\overline{A}_{x+t} - \\overline{P}(\\overline{A}_x) \\cdot \\overline{a}_{x+t}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "t", type: "float", label: "时刻" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["Ax_continuous", "ax_continuous", "Px_continuous"],
    isLeaf: false,
    sourceFile: "chapter12_clean.md",
  },
  {
    id: "thiele_ode",
    symbol: "Thiele ODE",
    latex: "\\frac{d}{dt}{}_t \\overline{V} = \\pi_t + [\\delta + \\mu_x(t)]{}_t \\overline{V} - b_t \\mu_x(t)",
    category: "净准备金（完全连续）",
    chapter: 12,
    subcategory: "微分方程",
    definition: "Thiele微分方程：净准备金变化率 = 保费 + 利息 - 死亡风险成本",
    formulaLatex: "\\frac{d}{dt}{}_t \\overline{V} = \\pi_t + [\\delta + \\mu_x(t)] \\cdot {}_t \\overline{V} - b_t \\cdot \\mu_x(t)",
    inputs: [
      { name: "t", type: "float", label: "时刻" },
    ],
    outputs: [],
    dependencies: ["tV_continuous", "mu_x_t", "t_px"],
    isLeaf: false,
    sourceFile: "chapter12_clean.md",
  },
  {
    id: "tV_formula_d",
    symbol: "_tV̄ = 1 − ā_{x+t}/ā_x",
    latex: "{}_t \\overline{V} = 1 - \\frac{\\overline{a}_{x+t}}{\\overline{a}_x}",
    category: "净准备金（完全连续）",
    chapter: 12,
    subcategory: "恒等变形",
    definition: "用年金比表示的净准备金：_tV̄ = 1 − ā_{x+t}/ā_x",
    formulaLatex: "{}_t \\overline{V}(\\overline{A}_x) = 1 - \\frac{\\overline{a}_{x+t}}{\\overline{a}_x} = \\frac{\\overline{A}_{x+t} - \\overline{A}_x}{1 - \\overline{A}_x}",
    inputs: [
      { name: "x", type: "int", label: "签约年龄" },
      { name: "t", type: "float", label: "时刻" },
      { name: "i", type: "float", label: "利率", default: 0.035 },
    ],
    outputs: [{ name: "value", type: "float", label: "净准备金" }],
    dependencies: ["ax_continuous", "Ax_continuous"],
    isLeaf: false,
    sourceFile: "chapter12_clean.md",
  },
];

// ================================================================
// 第九章：费用负荷保费 (chapter9_clean.md) — 简要条目
// ================================================================

const CH9_FORMULAS: FormulaEntry[] = [
  {
    id: "expense_loaded_premium",
    symbol: "G",
    latex: "G",
    category: "费用负荷保费",
    chapter: 9,
    subcategory: "费用负荷",
    definition: "费用负荷保费：G = 净保费 + 费用附加。满足 G·ä = E(Z) + E(费用)",
    formulaLatex: "G \\cdot \\ddot{a} = E(Z) + E(\\text{费用})",
    inputs: [
      { name: "net_premium", type: "float", label: "净保费" },
      { name: "expense_rate", type: "float", label: "费用率" },
    ],
    outputs: [{ name: "value", type: "float", label: "费用负荷保费" }],
    dependencies: ["Px_discrete", "ax_due_discrete"],
    isLeaf: false,
    sourceFile: "chapter9_clean.md",
  },
];

// ================================================================
// 中间计算步骤（用于展示推导链）
// ================================================================

const INTERMEDIATE_FORMULAS: FormulaEntry[] = [
  {
    id: "interest_rate",
    symbol: "i",
    latex: "i",
    category: "经济假设",
    chapter: 0,
    subcategory: "利率",
    definition: "年有效利率（经济假设参数）",
    formulaLatex: "i = \\text{年有效利率}",
    inputs: [{ name: "i", type: "float", label: "利率" }],
    outputs: [{ name: "value", type: "float", label: "i" }],
    dependencies: [],
    isLeaf: true,
    sourceFile: "",
  },
  {
    id: "v_factor",
    symbol: "v^n",
    latex: "v^n",
    category: "中间计算",
    chapter: 0,
    subcategory: "贴现因子",
    definition: "n年期贴现因子：v^n = (1+i)^{-n}",
    formulaLatex: "v^n = (1+i)^{-n} = e^{-\\delta n}",
    inputs: [
      { name: "i", type: "float", label: "利率" },
      { name: "n", type: "int", label: "年数" },
    ],
    outputs: [{ name: "value", type: "float", label: "v^n" }],
    dependencies: [],
    isLeaf: false,
    sourceFile: "",
  },
  {
    id: "d_factor",
    symbol: "d",
    latex: "d",
    category: "中间计算",
    chapter: 0,
    subcategory: "贴现率",
    definition: "贴现率：d = i/(1+i) = 1 − v",
    formulaLatex: "d = \\frac{i}{1+i} = 1 - v",
    inputs: [{ name: "i", type: "float", label: "利率" }],
    outputs: [{ name: "value", type: "float", label: "d" }],
    dependencies: [],
    isLeaf: false,
    sourceFile: "",
  },
  {
    id: "delta_factor",
    symbol: "δ",
    latex: "\\delta",
    category: "中间计算",
    chapter: 0,
    subcategory: "利息力",
    definition: "利息力：δ = ln(1+i)",
    formulaLatex: "\\delta = \\ln(1+i)",
    inputs: [{ name: "i", type: "float", label: "利率" }],
    outputs: [{ name: "value", type: "float", label: "δ" }],
    dependencies: [],
    isLeaf: false,
    sourceFile: "",
  },
];

// ================================================================
// 核心定理/公式（用于 Theorem 节点展示推导依据）
// ================================================================

const T: FormulaEntry[] = [
  { id:"thm_pure_endowment",symbol:"_nE_x=v^n·_np_x",latex:"{}_nE_x=v^n{}_np_x",category:"定理",chapter:4,subcategory:"生存保险",definition:"n年期生存保险精算现值（结论4.2.1）",formulaLatex:"{}_nE_x=v^n·{}_np_x=v^n l_{x+n}/l_x",inputs:[],outputs:[],dependencies:["t_px"],isLeaf:false,
    proof: "设被保险人在第 $n$ 年末生存时给付 1 元。\n给付额现值：$Z = v^n \\cdot I(T(x) > n)$。\n取期望：$E[Z] = v^n \\cdot P(T(x) > n)$。\n$P(T(x) > n) = {}_np_x$（$x$ 岁个体活过 $x+n$ 岁的概率）。\n$\\therefore {}_nE_x = v^n \\cdot {}_np_x$。\n用生命表：${}_np_x = l_{x+n}/l_x$， \\therefore {}_nE_x = v^n l_{x+n}/l_x$。",
    sourceFile:"chapter4_clean.md"},
  { id:"thm_A_term_disc",symbol:"A¹=Σv^{k+1}·_kp_x·q_{x+k}",latex:"A^1=\\sum v^{k+1}{}_kp_x q_{x+k}",category:"定理",chapter:4,subcategory:"定期寿险",definition:"离散定期寿险精算现值（结论4.3.3）",formulaLatex:"A^1_{x:n}=\\sum v^{k+1}{}_kp_x q_{x+k}",inputs:[],outputs:[],dependencies:["Ax_term_discrete"],isLeaf:false,
    proof: "设被保险人在死亡保单年度末给付 1 元。\n给付时刻为 $K(x)+1$（$K$ = 未来生存整年数）。\n给付额现值：$Z = v^{K+1} \\cdot I(K \\le n-1)$。\n按 $K$ 的分布求和：\n$E[Z] = \\sum_{k=0}^{n-1} v^{k+1} \\cdot P(K=k)$。\n$P(K=k) = {}_kp_x \\cdot q_{x+k}$（活 $k$ 年后在第 $k+1$ 年死亡）。\n$\\therefore A^1_{x:\\overline{n|}} = \\sum_{k=0}^{n-1} v^{k+1} \\cdot {}_kp_x \\cdot q_{x+k}$。",
    sourceFile:"chapter4_clean.md"},
  { id:"thm_udd_relation",symbol:"Ā¹=(i/δ)·A¹",latex:"\\overline{A}^1=\\frac{i}{\\delta}A^1",category:"定理",chapter:4,subcategory:"UDD关系",definition:"UDD下连续与离散精算现值的关系（结论4.3.4）",formulaLatex:"\\overline{A}^1=(i/\\delta)A^1",inputs:[],outputs:[],dependencies:[],isLeaf:false,
    proof: "在 UDD（每一年龄年死亡均匀分布）假设下：\n$\\mu_x(t) = \\frac{q_x}{1-t\\cdot q_x}$， $0 \\le t < 1$。\n$\\overline{A}^1_{x:\\overline{n|}} = \\int_0^n v^t \\cdot {}_tp_x \\cdot \\mu_x(t) dt$。\n在 UDD 下将积分化为与离散值的关系（结论 4.3.4）：\n$\\overline{A}^1_{x:\\overline{n|}} = \\frac{i}{\\delta} \\cdot A^1_{x:\\overline{n|}}$。\n其中 $i$ 为年有效利率，$\\delta = \\ln(1+i)$ 为利息力。",
    sourceFile:"chapter4_clean.md"},
  { id:"thm_constant_force_Ax",symbol:"Ā_x=μ/(μ+δ)",latex:"\\overline{A}_x=\\frac{\\mu}{\\mu+\\delta}",category:"定理",chapter:4,subcategory:"终身寿险",definition:"常数死亡力下终身寿险精算现值",formulaLatex:"\\overline{A}_x=\\mu/(\\mu+\\delta)",inputs:[],outputs:[],dependencies:["Ax_continuous"],isLeaf:false,
    proof: "常数死亡力假设：$\\mu(x) \\equiv \\mu$。\n则 ${}_tp_x = \\exp(-\\int_0^t \\mu ds) = e^{-\\mu t}$。\n贴现因子 $v^t = e^{-\\delta t}$（$\\delta$ = 利息力）。\n$\\overline{A}_x = \\int_0^\\infty v^t \\cdot {}_tp_x \\cdot \\mu_x(t) dt$\n$= \\int_0^\\infty e^{-\\delta t} \\cdot e^{-\\mu t} \\cdot \\mu dt$\n$= \\mu \\int_0^\\infty e^{-(\\mu+\\delta)t} dt$\n$= \\mu \\cdot \\frac{1}{\\mu+\\delta} = \\frac{\\mu}{\\mu+\\delta}$。",
    sourceFile:"chapter4_clean.md"},
  { id:"thm_recurrence_Ax",symbol:"A_x=vq_x+vp_xA_{x+1}",latex:"A_x=vq_x+vp_xA_{x+1}",category:"定理",chapter:4,subcategory:"递推公式",definition:"终身寿险的递推关系",formulaLatex:"A_x=vq_x+vp_xA_{x+1}",inputs:[],outputs:[],dependencies:["Ax_discrete"],isLeaf:false,
    proof: "$A_x = \\sum_{k=0}^\\infty v^{k+1} \\cdot {}_kp_x \\cdot q_{x+k}$\n分离 $k=0$ 项：$A_x = v\\cdot q_x + \\sum_{k=1}^\\infty v^{k+1} \\cdot {}_kp_x \\cdot q_{x+k}$。\n对第二项：${}_kp_x = p_x \\cdot {}_{k-1}p_{x+1}$（$k \\ge 1$）。\n令 $j=k-1$：$v^{k+1}{}_kp_x q_{x+k} = v\\cdot p_x \\cdot v^{j+1}{}_jp_{x+1}q_{x+1+j}$。\n$\\sum_{k=1}^\\infty = v\\cdot p_x \\sum_{j=0}^\\infty v^{j+1}{}_jp_{x+1}q_{x+1+j} = v p_x A_{x+1}$。\n$\\therefore A_x = v q_x + v p_x A_{x+1}$。",
    sourceFile:"chapter4_clean.md"},
  { id:"thm_ax_due_disc",symbol:"ä_x=Σv^k·_kp_x",latex:"\\ddot{a}_x=\\sum v^k{}_kp_x",category:"定理",chapter:5,subcategory:"期初年金",definition:"离散期初生存年金精算现值（结论5.4.1）",formulaLatex:"\\ddot{a}_x=\\sum v^k{}_kp_x",inputs:[],outputs:[],dependencies:["ax_due_discrete"],isLeaf:false,
    proof: "每年年初给付 1 元的终身生存年金。\n给付额现值：$Y = \\sum_{k=0}^{K(x)} v^k$。\n取期望：$\\ddot{a}_x = E[Y] = \\sum_{k=0}^\\infty v^k \\cdot P(K(x) \\ge k)$。\n$P(K(x) \\ge k) = {}_kp_x$（活过 $x+k$ 岁的概率）。\n$\\therefore \\ddot{a}_x = \\sum_{k=0}^\\infty v^k \\cdot {}_kp_x$。\n注：$a_x = \\ddot{a}_x - 1$（期末年金 = 期初年金 - 首付的 1）。",
    sourceFile:"chapter5_clean.md"},
  { id:"thm_ax_cont_cf",symbol:"ā_x=1/(μ+δ)",latex:"\\overline{a}_x=\\frac{1}{\\mu+\\delta}",category:"定理",chapter:5,subcategory:"连续年金",definition:"常数死亡力下连续年金精算现值",formulaLatex:"\\overline{a}_x=1/(\\mu+\\delta)",inputs:[],outputs:[],dependencies:["ax_continuous"],isLeaf:false,
    proof: "常数死亡力下：${}_tp_x = e^{-\\mu t}$, $v^t = e^{-\\delta t}$。\n$\\overline{a}_x = \\int_0^\\infty v^t \\cdot {}_tp_x dt$\n$= \\int_0^\\infty e^{-\\delta t} \\cdot e^{-\\mu t} dt$\n$= \\int_0^\\infty e^{-(\\mu+\\delta)t} dt$\n$= \\left[\\frac{e^{-(\\mu+\\delta)t}}{-(\\mu+\\delta)}\\right]_0^\\infty$\n$= \\frac{1}{\\mu+\\delta}$。",
    sourceFile:"chapter5_clean.md"},
  { id:"thm_identity_disc",symbol:"d·ä_x+A_x=1",latex:"d\\ddot{a}_x+A_x=1",category:"定理",chapter:5,subcategory:"恒等式",definition:"离散保险-年金恒等式",formulaLatex:"d\\ddot{a}_x+A_x=1",inputs:[],outputs:[],dependencies:[],isLeaf:false,
    proof: "由 $\\ddot{a}_x = \\sum_{k=0}^\\infty v^k {}_kp_x$ 和 $A_x = \\sum_{k=0}^\\infty v^{k+1}{}_kp_x q_{x+k}$。\n注意到 $q_{x+k} = 1 - p_{x+k}$ 且 $p_{x+k} = {}_{k+1}p_x/{}_kp_x$。\n计算 $d\\ddot{a}_x + A_x$：\n$d\\ddot{a}_x = (1-v)\\sum v^k{}_kp_x = \\sum v^k{}_kp_x - \\sum v^{k+1}{}_kp_x$\n$A_x = \\sum v^{k+1}{}_kp_x q_{x+k} = \\sum v^{k+1}({}_kp_x - {}_{k+1}p_x)$\n相加：$d\\ddot{a}_x + A_x = \\sum v^k{}_kp_x - \\sum v^{k+1}{}_{k+1}p_x$\n第二项令 $j=k+1$：$\\sum_{j=1}^\\infty v^j{}_jp_x$。与第一项相消，仅剩 $k=0$ 项 $v^0{}_0p_x = 1$。\n$\\therefore d\\ddot{a}_x + A_x = 1$。",
    sourceFile:"chapter5_clean.md"},
  { id:"thm_net_premium",symbol:"P=A/ä",latex:"P=\\frac{A}{\\ddot{a}}",category:"定理",chapter:8,subcategory:"净保费",definition:"均衡净保费（平衡准则E(L)=0）",formulaLatex:"P_x=A_x/\\ddot{a}_x=1/\\ddot{a}_x-d",inputs:[],outputs:[],dependencies:["Px_discrete"],isLeaf:false,
    proof: "均衡准则：$E(L) = 0$。\n$L = v^{K+1} - P_x \\cdot \\ddot{a}_{\\overline{K+1|}}$。\n$E(L) = E[v^{K+1}] - P_x \\cdot E[\\ddot{a}_{\\overline{K+1|}}]$。\n$E[v^{K+1}] = A_x$（死亡保单年度末给付的终身寿险精算现值）。\n$E[\\ddot{a}_{\\overline{K+1|}}] = \\ddot{a}_x$（期初终身生存年金精算现值）。\n$\\therefore A_x - P_x \\cdot \\ddot{a}_x = 0$。\n$\\Rightarrow P_x = \\frac{A_x}{\\ddot{a}_x}$。\n变形：$P_x = \\frac{1-d\\ddot{a}_x}{\\ddot{a}_x} = \\frac{1}{\\ddot{a}_x} - d$。",
    sourceFile:"chapter8_clean.md"},
  { id:"thm_net_premium_cont",symbol:"P̄=Ā/ā",latex:"\\overline{P}=\\frac{\\overline{A}}{\\overline{a}}",category:"定理",chapter:8,subcategory:"净保费",definition:"完全连续均衡净保费",formulaLatex:"\\overline{P}=\\overline{A}_x/\\overline{a}_x=1/\\overline{a}_x-\\delta",inputs:[],outputs:[],dependencies:["Px_continuous"],isLeaf:false,
    proof: "完全连续情形：$L = v^T - \\overline{P} \\cdot \\overline{a}_{\\overline{T|}}$。\n$E(L) = \\overline{A}_x - \\overline{P} \\cdot \\overline{a}_x = 0$。\n$\\Rightarrow \\overline{P} = \\frac{\\overline{A}_x}{\\overline{a}_x}$。\n利用恒等式 $\\delta\\overline{a}_x + \\overline{A}_x = 1$：\n$\\overline{P} = \\frac{1-\\delta\\overline{a}_x}{\\overline{a}_x} = \\frac{1}{\\overline{a}_x} - \\delta$。\n或 $\\overline{P} = \\frac{\\delta\\overline{A}_x}{1-\\overline{A}_x}$。",
    sourceFile:"chapter8_clean.md"},
  { id:"thm_prospective_reserve",symbol:"_kV=A_{x+k}−P·ä_{x+k}",latex:"{}_kV_x=A_{x+k}-P_x\\ddot{a}_{x+k}",category:"定理",chapter:10,subcategory:"净准备金",definition:"将来法净准备金（定理10.3.1）",formulaLatex:"{}_kV_x=A_{x+k}-P_x\\ddot{a}_{x+k}",inputs:[],outputs:[],dependencies:["kVx_discrete"],isLeaf:false,
    proof: "将来法（定理 10.3.1）：\n${}_kV_x = $（未来保险给付在 $x+k$ 岁的精算现值）\n$- P_x \\cdot$（未来保费收入在 $x+k$ 岁的精算现值）。\n未来保险给付现值 $= A_{x+k}$。\n未来保费现值 $= P_x \\cdot \\ddot{a}_{x+k}$。\n$\\therefore {}_kV_x = A_{x+k} - P_x \\cdot \\ddot{a}_{x+k}$。\n等价形式：\n保费差：${}_kV_x = A_{x+k} - \\frac{A_x}{\\ddot{a}_x}\\ddot{a}_{x+k} = (P_{x+k} - P_x)\\ddot{a}_{x+k}$。\n缴清保险：${}_kV_x = A_{x+k} - P_x\\ddot{a}_{x+k} = A_{x+k}(1-\\frac{P_x}{P_{x+k}})$。",
    sourceFile:"chapter10_clean.md"},
  { id:"thm_fackler",symbol:"_{k+1}V=((_kV+P)(1+i)−q)/p",latex:"{}_{k+1}V=\\frac{({}_kV+P)(1+i)-q}{p}",category:"定理",chapter:11,subcategory:"递推公式",definition:"Fackler递推公式",formulaLatex:"{}_{k+1}V=(({}_kV+P)(1+i)-q_{x+k})/p_{x+k}",inputs:[],outputs:[],dependencies:["fackler_recursion"],isLeaf:false,
    proof: "由定理 10.3.2 准备金递推关系：\n${}_kV + P = v \\cdot q_{x+k} \\cdot 1 + v \\cdot p_{x+k} \\cdot {}_{k+1}V$。\n含义：年初资金 = 死亡给付精算现值 + 生存续转精算现值。\n解出 ${}_{k+1}V$：\n$v p_{x+k} {}_{k+1}V = {}_kV + P - v q_{x+k}$。\n${}_{k+1}V = \\frac{({}_kV + P) - v q_{x+k}}{v p_{x+k}}$。\n以 $v = 1/(1+i)$ 代入：${}_{k+1}V = \\frac{({}_kV + P)(1+i) - q_{x+k}}{p_{x+k}}$。\n初始条件：${}_0V = 0$（均衡保费保证初始准备金为零）。",
    sourceFile:"chapter11_clean.md"},
  { id:"thm_hattendorf",symbol:"Var(_hL)=Σv^{2j}Var(Λ_j)",latex:"\\mathrm{Var}({}_hL)=\\sum v^{2(j-h)}\\mathrm{Var}(\\Lambda_j)",category:"定理",chapter:10,subcategory:"方差分解",definition:"Hattendorf定理（定理10.5.1）",formulaLatex:"\\mathrm{Var}[{}_hL|K\\ge h]=\\sum v^{2(j-h)}\\mathrm{Var}[\\Lambda_j]",inputs:[],outputs:[],dependencies:["hattendorf"],isLeaf:false,
    proof: "定义 $\\Lambda_h$（第 $h+1$ 年考虑准备金变化的资金损失现值）：\n$\\Lambda_h = v(b_{h+1} - {}_{h+1}V) I(K=h) - (P+{}_hV - v{}_{h+1}V) I(K \\ge h)$。\n结论 10.4.1(b)：$E[\\Lambda_h | K \\ge h] = 0$。\n（由递推公式 $v b_{h+1} q_{x+h} - P - {}_hV + v p_{x+h} {}_{h+1}V = 0$ 保证）\n结论 10.4.1(d)：$\\mathrm{Var}[\\Lambda_h | K \\ge h] = [v(b_{h+1}-{}_{h+1}V)]^2 \\cdot p_{x+h} \\cdot q_{x+h}$。\n（死亡项 $I(K=h)$ 的方差 = 成功概率为 $q_{x+h}$ 的伯努利方差 $(v\\Delta)^2 q(1-q)$）\n结论 10.4.1(e)：不同 $h \\ne j$ 时 $\\mathrm{Cov}(\\Lambda_h, \\Lambda_j | K \\ge g) = 0$。\n定理 10.5.1：各年独立，\n$\\mathrm{Var}[{}_hL | K \\ge h] = \\sum_{j=h}^\\infty v^{2(j-h)} \\mathrm{Var}[\\Lambda_j | K \\ge j] \\cdot {}_{j-h}p_{x+h}$。",
    sourceFile:"chapter10_clean.md"},
  { id:"thm_endowment_decomp",symbol:"A_{x:n}=A¹+_nE_x",latex:"A_{x:\\overline{n|}}=A^1+{}_nE_x",category:"定理",chapter:4,subcategory:"生死合险",definition:"结论4.5.1：生死合险=死亡保险+生存保险",formulaLatex:"A_{x:n}=A^1_{x:n}+{}_nE_x",inputs:[],outputs:[],dependencies:[],isLeaf:false,
    sourceFile:"chapter4_clean.md"},
  { id:"thm_lambda_h",symbol:"Λ_h=v(b−V)I(K=h)−(P+V−vV)I(K≥h)",latex:"\\Lambda_h=v(b-{}_{h+1}V)I(K=h)-(P+{}_hV-v{}_{h+1}V)I(K\\ge h)",category:"定理",chapter:10,subcategory:"资金损失",definition:"考虑准备金变化的资金损失现值",formulaLatex:"\\Lambda_h=v(b_{h+1}-{}_{h+1}V)I(K=h)-(P+{}_hV-v{}_{h+1}V)I(K\\ge h)",inputs:[],outputs:[],dependencies:["Lambda_h"],isLeaf:false,
    proof: "考虑准备金变化后，第 $h+1$ 年的资金损失 $\\Lambda_h$：\n死亡路径 $(K=h)$：保险人需给付 $b_{h+1}$，\n同时释放年末准备金 ${}_{h+1}V$（不再需要持有）。\n$\\therefore$ 净支出现值 $= v(b_{h+1} - {}_{h+1}V)$。\n生存路径 $(K \\ge h+1)$：年初持有准备金 ${}_hV$，\n收到保费 $P$，年末准备金变为 $v{}_{h+1}V$。\n$\\therefore$ 净收入 $= P + {}_hV - v{}_{h+1}V$。\n综合：$\\Lambda_h = v(b_{h+1} - {}_{h+1}V)I(K=h) - (P+{}_hV - v{}_{h+1}V)I(K\\ge h)$。\n注意 $E[\\Lambda_h | K \\ge h] = 0$（由定理 10.3.2 的递推公式保证）。",
    sourceFile:"chapter10_clean.md"},
  { id:"thm_var_lambda",symbol:"Var(Λ_h)=[v(b−V)]²·p·q",latex:"\\mathrm{Var}(\\Lambda_h)=[v(b-{}_{h+1}V)]^2p_{x+h}q_{x+h}",category:"定理",chapter:10,subcategory:"方差分解",definition:"结论10.4.1：Λ_h的条件方差",formulaLatex:"\\mathrm{Var}(\\Lambda_h|K\\ge h)=[v(b-{}_{h+1}V)]^2p_{x+h}q_{x+h}",inputs:[],outputs:[],dependencies:["Lambda_h"],isLeaf:false,
    proof: "由 $E[\\Lambda_h | K \\ge h] = 0$（递推保证）：\n$\\mathrm{Var}[\\Lambda_h | K \\ge h] = E[\\Lambda_h^2 | K \\ge h]$。\n当 $K \\ge h$ 时，$\\Lambda_h$ 取值：\n以概率 $q_{x+h}$：$\\Lambda_h = v(b_{h+1} - {}_{h+1}V)$（死亡路径）。\n以概率 $p_{x+h}$：$\\Lambda_h = -(P+{}_hV - v{}_{h+1}V)$（生存路径）。\n由递推 $P+{}_hV - v{}_{h+1}V = v(b_{h+1}-{}_{h+1}V)\\cdot q_{x+h}/p_{x+h}$。\n$\\therefore \\mathrm{Var}[\\Lambda_h | K \\ge h]$\n$= [v(b_{h+1}-{}_{h+1}V)]^2 \\cdot q_{x+h} + [v(b_{h+1}-{}_{h+1}V)\\frac{q_{x+h}}{p_{x+h}}]^2 \\cdot p_{x+h}$\n$= [v(b_{h+1}-{}_{h+1}V)]^2 \\cdot q_{x+h}(1 + \\frac{q_{x+h}}{p_{x+h}})$\n$= [v(b_{h+1}-{}_{h+1}V)]^2 \\cdot p_{x+h} \\cdot q_{x+h}$（化简得）。",
    sourceFile:"chapter10_clean.md"},
  { id:"thm_var_L_cont",symbol:"Var(L)=Var(vᵀ)/(δā)²",latex:"\\mathrm{Var}(L)=\\frac{\\mathrm{Var}(v^T)}{(\\delta\\overline{a}_x)^2}",category:"定理",chapter:8,subcategory:"签单损失",definition:"结论8.4.2：完全连续签单损失方差",formulaLatex:"\\mathrm{Var}(L)=\\mathrm{Var}(v^T)/(\\delta\\overline{a}_x)^2",inputs:[],outputs:[],dependencies:[],isLeaf:false,
    proof: "结论 8.4.2 证明：\n$L = v^T - \\overline{P} \\cdot \\overline{a}_{\\overline{T|}}$。\n年金现值 $\\overline{a}_{\\overline{T|}} = \\frac{1-v^T}{\\delta}$。\n代入：$L = v^T - \\overline{P} \\cdot \\frac{1-v^T}{\\delta}$。\n$= v^T(1+\\frac{\\overline{P}}{\\delta}) - \\frac{\\overline{P}}{\\delta}$。\n$\\overline{P} = \\frac{\\overline{A}_x}{\\overline{a}_x}$，且 $\\delta\\overline{a}_x = 1-\\overline{A}_x$。\n$1+\\frac{\\overline{P}}{\\delta} = 1+\\frac{\\overline{A}_x}{\\delta\\overline{a}_x} = 1+\\frac{\\overline{A}_x}{1-\\overline{A}_x} = \\frac{1}{1-\\overline{A}_x}$。\n$L = \\frac{v^T - \\overline{A}_x}{1-\\overline{A}_x} = \\frac{v^T - \\overline{A}_x}{\\delta\\overline{a}_x}$。\n$\\mathrm{Var}(L) = \\frac{\\mathrm{Var}(v^T)}{(\\delta\\overline{a}_x)^2} = \\frac{{}^2\\overline{A}_x - \\overline{A}_x^2}{(1-\\overline{A}_x)^2}$。\n例 8.4.4 中：$\\frac{\\mathrm{Var}(v^T)}{\\mathrm{Var}(L)} = (\\delta\\overline{a}_x)^2 = (1-\\overline{A}_x)^2 = 0.36$。\n$\\therefore 1-\\overline{A}_x = 0.6$， $\\overline{A}_x = 0.4$。",
    sourceFile:"chapter8_clean.md"},
  { id:"thm_mu_def",symbol:"μ(t)=f_X/s",latex:"\\mu(t)=\\frac{f_X(t)}{s(t)}",category:"定义",chapter:1,subcategory:"死亡力",definition:"死亡力的定义",formulaLatex:"\\mu(t)=f_X(t)/s(t)=-s'(t)/s(t)",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter1_clean.md"},
  { id:"thm_s_from_mu",symbol:"s(t)=exp(−∫μ)",latex:"s(t)=\\exp(-\\int_0^t\\mu)",category:"定理",chapter:1,subcategory:"生存分布",definition:"结论1.2.1",formulaLatex:"s(t)=\\exp(-\\int_0^t\\mu(s)ds)",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter1_clean.md"},
  { id:"thm_tpx_def",symbol:"_tp_x=s(x+t)/s(x)",latex:"{}_tp_x=\\frac{s(x+t)}{s(x)}",category:"定义",chapter:1,subcategory:"生存概率",definition:"结论1.3.1",formulaLatex:"{}_tp_x=s(x+t)/s(x)",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter1_clean.md"},
  { id:"thm_tpx_from_l",symbol:"_tp_x=l_{x+t}/l_x",latex:"{}_tp_x=\\frac{l_{x+t}}{l_x}",category:"定理",chapter:1,subcategory:"生命表",definition:"结论1.5.1",formulaLatex:"{}_tp_x=l_{x+t}/l_x",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter1_clean.md"},
  { id:"thm_complete_ex_def",symbol:"ė₀=∫s(t)dt",latex:"\\mathring{e}_0=\\int s(t)dt",category:"定义",chapter:1,subcategory:"平均余命",definition:"结论1.2.2",formulaLatex:"\\mathring{e}_0=\\int_0^\\infty s(t)dt=E[X]",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter1_clean.md"},
  { id:"thm_de_moivre_s",symbol:"s(t)=(ω−t)/ω",latex:"s(t)=\\frac{\\omega-t}{\\omega}",category:"定理",chapter:1,subcategory:"死亡力模型",definition:"De Moivre生存函数",formulaLatex:"s(t)=(\\omega-t)/\\omega",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter1_clean.md"},
  { id:"thm_de_moivre_mu",symbol:"μ(t)=1/(ω−t)",latex:"\\mu(t)=\\frac{1}{\\omega-t}",category:"定理",chapter:1,subcategory:"死亡力模型",definition:"De Moivre死亡力",formulaLatex:"\\mu(t)=1/(\\omega-t)",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter1_clean.md"},
  { id:"thm_Ax_cont_def",symbol:"Ā_x=∫v^t·_tp_x·μ_x dt",latex:"\\overline{A}_x=\\int v^t{}_tp_x\\mu_x dt",category:"定义",chapter:4,subcategory:"终身寿险",definition:"连续终身寿险的积分定义",formulaLatex:"\\overline{A}_x=\\int_0^\\infty v^t{}_tp_x\\mu_x(t)dt",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter4_clean.md"},
  { id:"thm_ax_cont_def",symbol:"ā_x=∫v^t·_tp_x dt",latex:"\\overline{a}_x=\\int v^t{}_tp_x dt",category:"定义",chapter:5,subcategory:"连续年金",definition:"结论5.3.1",formulaLatex:"\\overline{a}_x=\\int_0^\\infty v^t{}_tp_x dt",inputs:[],outputs:[],dependencies:[],isLeaf:false,sourceFile:"chapter5_clean.md"},
];

export const ALL_FORMULAS: FormulaEntry[] = [
  ...CH1_FORMULAS,
  ...CH4_FORMULAS,
  ...CH5_FORMULAS,
  ...CH8_FORMULAS,
  ...CH9_FORMULAS,
  ...CH10_FORMULAS,
  ...CH11_FORMULAS,
  ...CH12_FORMULAS,
  ...INTERMEDIATE_FORMULAS,
  ...T,
];

export const FORMULA_BY_ID = new Map(ALL_FORMULAS.map(f => [f.id, f]));

export const FORMULAS_BY_CHAPTER = new Map<number, FormulaEntry[]>();
ALL_FORMULAS.forEach(f => {
  const arr = FORMULAS_BY_CHAPTER.get(f.chapter) || [];
  arr.push(f);
  FORMULAS_BY_CHAPTER.set(f.chapter, arr);
});

export const LEAF_FORMULAS = ALL_FORMULAS.filter(f => f.isLeaf);
export const DERIVED_FORMULAS = ALL_FORMULAS.filter(f => !f.isLeaf);
